"""Add skin_type and settings fields

Revision ID: 0e0ba916eedb
Revises: 951d3088bf2f
Create Date: 2026-01-04 22:42:08.288614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e0ba916eedb'
down_revision = '951d3088bf2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skin_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('dark_mode', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notifications_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('notifications_enabled')
        batch_op.drop_column('dark_mode')
        batch_op.drop_column('skin_type')

    # ### end Alembic commands ###
