"""Add analysis fields to User

Revision ID: 951d3088bf2f
Revises: 93a2fc49f415
Create Date: 2026-01-04 22:25:11.170872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951d3088bf2f'
down_revision = '93a2fc49f415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skin_tone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('body_shape', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('color_palette', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('style_vibe', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('style_vibe')
        batch_op.drop_column('color_palette')
        batch_op.drop_column('body_shape')
        batch_op.drop_column('skin_tone')

    # ### end Alembic commands ###
